import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Button } from "@/components/Button";
import { EmptyState } from "@/components/EmptyState";
import { PageHeader } from "@/components/PageHeader";
import { Textarea } from "@/components/Textarea";
import { getReviewQueue, reviewAction, type WorkflowComplaint } from "@/api/workflows";

export function ManualReview() {
  const [queue, setQueue] = useState<WorkflowComplaint[]>([]); const [selected, setSelected] = useState<WorkflowComplaint | null>(null); const [comment, setComment] = useState(""); const [action, setAction] = useState("approve"); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  async function refresh() { setLoading(true); try { setQueue(await getReviewQueue()); setError(null); } catch (e: any) { setError(e?.response?.data?.detail ?? "Unable to load review queue."); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); }, []);
  async function submit() { if (!selected || !comment.trim()) return; setSaving(true); try { await reviewAction(selected.id, action, { comment: comment.trim() }); setSelected(null); setComment(""); await refresh(); } catch (e: any) { setError(e?.response?.data?.detail ?? "Reviewer action failed."); } finally { setSaving(false); } }
  return <div><PageHeader title="Manual review" description="Live reviewer queue from the SupportNova backend." />{error && <p className="mb-3 rounded border border-danger/30 p-3 text-[13px] text-danger">{error}</p>}{loading ? <p className="text-[13px] text-ink-muted">Loading review queue…</p> : queue.length === 0 ? <EmptyState title="No cases in review" description="The backend has no pending review cases." /> : <div className="panel overflow-x-auto"><table className="w-full min-w-[700px] text-left text-[13px]"><thead><tr className="border-b border-line bg-canvas-subtle text-[11px] uppercase text-ink-muted"><th className="px-3 py-2">ID</th><th className="px-3 py-2">Issue</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Review</th></tr></thead><tbody>{queue.map((c) => <tr key={c.id} className="border-b border-line"><td className="px-3 py-2"><Link className="text-primary hover:underline" to={`/complaints/${c.id}`}>{c.id}</Link></td><td className="px-3 py-2">{c.title}</td><td className="px-3 py-2">{c.status}</td><td className="px-3 py-2"><Button size="sm" onClick={() => setSelected(c)}>Review</Button></td></tr>)}</tbody></table></div>}
  {selected && <div className="fixed inset-0 z-50 grid place-items-center bg-black/30 p-4"><div className="w-full max-w-lg rounded-lg bg-surface p-5 shadow-xl"><h2 className="mb-3 font-semibold">Review {selected.id}</h2><label className="block text-[13px]">Action<select className="mt-1 w-full rounded border p-2" value={action} onChange={(e) => setAction(e.target.value)}><option value="approve">Approve</option><option value="modify">Modify</option><option value="reject">Reject</option><option value="escalate">Escalate</option><option value="comment">Comment</option><option value="regenerate-response">Regenerate response</option></select></label><Textarea className="mt-3" label="Comment" value={comment} onChange={(e) => setComment(e.target.value)} rows={4} /><div className="mt-4 flex justify-end gap-2"><Button variant="outline" onClick={() => setSelected(null)}>Cancel</Button><Button disabled={saving || !comment.trim()} onClick={() => void submit()}>{saving ? "Saving…" : "Submit"}</Button></div></div></div>}</div>;
}
